name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker -- --tag=awx-ee:${{ github.event.release.tag_name }}
          docker tag awx-ee:${{ github.event.release.tag_name }} awx-ee:latest
          
      - name: Downcase repo path
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
      - name: Push awx-ee
        uses: redhat-actions/push-to-registry@v2.3.1
        with:
          image: awx-ee
          tags: latest ${{ github.event.release.tag_name }}
          registry: ghcr.io/${{ env.REPO }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
